coverage:
  # if there's a manual merge, we can drop
  range: "95..100"
  # but otherwise, all PRs should be 100%
  status:
    patch:
      default:
        target: 100%
    project:
      default:
        target: 0%
